setopt AUTO_CD
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

autoload -Uz bashcompinit && bashcompinit

zstyle ":completion:*" menu select
zstyle ":completion:*" insert-tab false
zstyle ':completion:*' special-dirs true

bindkey -v

export ANDROID_HOME=/opt/android-sdk
export NPM_CONFIG_PREFIX=$HOME/.npm-packages
export PUB_HOME=$HOME/.pub-cache
export GEM_HOME=$(ruby -e "print Gem.user_dir")

path=(
  $HOME/Codes/flutter/bin
  $HOME/.local/bin
  $NPM_CONFIG_PREFIX/bin
  $PUB_HOME/bin
  $GEM_HOME/bin
  $path
)
export PATH

export VISUAL=vim
export EDITOR=vim

source /usr/share/doc/pkgfile/command-not-found.zsh

alias ls="ls --color=auto"
alias la="ls -A"
alias ll="ls -alh --time-style=long-iso"
alias ln="ln -v"
alias grep="grep --color=auto"

alias vim=nvim

eval $(hub alias -s)
eval $(thefuck --alias)

source ~/.zsh/base16-shell/scripts/base16-onedark.sh

source ~/.zsh/antigen/antigen.zsh

antigen bundle mafredri/zsh-async

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen bundle sindresorhus/pure

antigen apply

bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
